//* template for story objects

//* story as a parent

const parentStory = {
  id: '',
  title: '',
  subtitle: '',
  article_text: '',
  article_link: '',
  notes: '',
  photo: '',
  type: '',
  copies_required: false,
  number_of_copies: 0,
  copies_sent: false,
  number_of_copies: 0,
  photo_uploaded: false,
  fact_check_required: true,
  fact_check_completed: true,
  graphic_image_required: false,
  graphic_image_completed: false,
  payment_required: false,
  payment_completed: true,
  external_link: '',
  word_count: 0,
  date_added: '',
  rough_draft_deadline: '',
  final_draft_deadline: '',
  publication_date: '',
  copies_destination: '',
  socials_required: false,
  socials_completed: false,
  underwriter_required: false,
  underwriter_completed: false,
  photo_submitted: false,
  photo_comments: '',
  contacts: [
    { ...childContact, story_association, invoice_amount, invoice_paid },
    {},
  ],
  theme: [{}, {}],
  tags: [{}, {}],
};

const childStory = {
  id: '',
  title: '',
  subtitle: '',
  article_text: '',
  article_link: '',
  notes: '',
  photo: '',
  type: '',
  copies_required: false,
  number_of_copies: 0,
  copies_sent: false,
  number_of_copies: 0,
  photo_uploaded: false,
  fact_check_required: true,
  fact_check_completed: true,
  graphic_image_required: false,
  graphic_image_completed: false,
  payment_required: false,
  payment_completed: true,
  external_link: '',
  word_count: 0,
  date_added: '',
  rough_draft_deadline: '',
  final_draft_deadline: '',
  publication_date: '',
  copies_destination: '',
  socials_required: false,
  socials_completed: false,
  underwriter_required: false,
  underwriter_completed: false,
  photo_submitted: false,
  photo_comments: '',
};
