import {DateTime} from 'luxon';


//* step 1: initial ideation. just title, notes, and tag

export const autofill1 = {
  id: '',
  title: 'women in tech bootcamps (working title)',
  subtitle: '',
  article_text: '',
  article_link: '',
  notes: 'had a great conversation with some people at Prime Digital Academy. potential feature?',
  photo: '',
  type: '',
  copies_required: false,
  number_of_copies: null,
  copies_sent: false,
  photo_uploaded: false,
  fact_check_completed: false,
  payment_required: false,
  payment_completed: false,
  socials_required: false,
  socials_completed: false,
  underwriter_required: false,
  underwriter_completed: false,
  photo_submitted: false,
  photo_comments: '',
  external_link: '',
  word_count: 0,
  date_added: '',
  rough_draft_deadline: DateTime.now(),
  final_draft_deadline: DateTime.now().toISO(),
  publication_date: DateTime.now().toISO(),
  contacts: [],
  theme: [],
  tags: [{id: 7, name: 'Technology', description: ''}],
};

//* step 2: go ahead with story. assign theme and dates

export const autofill2 = {
  id: '',
  title: 'women in tech bootcamps (working title)',
  subtitle: '',
  article_text: '',
  article_link: '',
  notes: 'had a great conversation with some people at Prime Digital Academy. potential feature?',
  photo: '',
  type: '',
  copies_required: false,
  number_of_copies: null,
  copies_sent: false,
  photo_uploaded: false,
  fact_check_required: true,
  fact_check_completed: false,
  payment_required: false,
  payment_completed: false,
  socials_required: true,
  socials_completed: false,
  underwriter_required: false,
  underwriter_completed: false,
  photo_submitted: false,
  photo_comments: 'picture of a student from prime',
  external_link: '',
  word_count: 500,
  date_added: '',
  rough_draft_deadline: DateTime.fromObject({day: 1, month: 8, year: 2023}).toISO(),
  final_draft_deadline: DateTime.fromObject({day: 15, month: 8, year: 2023}).toISO(),
  publication_date: DateTime.fromObject({day: 1, month: 9, year: 2023}).toISO(),
  contacts: [],
  theme: [{
    id: 9,
    name: 'Work',
    month_year: DateTime.fromISO('2023-09-01T05:00:00.000Z'),
    description: 'The ways our work lives are shifting — including the role of labor unions, anti-racist movements in the workplace, and changing family leave practices. Special sections: Directory, Elder, Travel & Adventure'
  }],
  tags: [{id: 7, name: 'Technology', description: ''}],
};

//* step 3: story is set. assign contacts. no autofill here.

export const autofill3 = {
  id: '',
  title: 'Accelerated: Women in Tech',
  subtitle: '',
  article_text: '',
  article_link: '',
  notes: 'had a great conversation with some people at Prime Digital Academy. potential feature? \t\ interviews with graduates, current students, alums',
  photo: '',
  type: '',
  copies_required: false,
  number_of_copies: null,
  copies_sent: false,
  photo_uploaded: false,
  fact_check_required: true,
  fact_check_completed: false,
  payment_required: false,
  payment_completed: false,
  socials_required: true,
  socials_completed: false,
  underwriter_required: false,
  underwriter_completed: false,
  photo_submitted: false,
  photo_comments: 'picture of a student from prime',
  external_link: '',
  word_count: 500,
  date_added: '',
  socials_required: false,
  socials_completed: false,
  underwriter_required: false,
  underwriter_completed: false,
  rough_draft_deadline: DateTime.fromObject({day: 1, month: 8, year: 2023}).toISO(),
  final_draft_deadline: DateTime.fromObject({day: 15, month: 8, year: 2023}).toISO(),
  publication_date: DateTime.fromObject({day: 1, month: 9, year: 2023}).toISO(),
  contacts: [],
  theme: [{
    id: 9,
    name: 'Work',
    month_year: DateTime.fromISO('2023-09-01T05:00:00.000Z'),
    description: 'The ways our work lives are shifting — including the role of labor unions, anti-racist movements in the workplace, and changing family leave practices. Special sections: Directory, Elder, Travel & Adventure'
  }],
  tags: [{id: 7, name: 'Technology', description: ''}],
};

//* step 4: 