import { DateTime } from 'luxon';


//* step 1: initial ideation. just title, notes, and tag

export const autofill1 = {
  id: '',
  title: 'women in tech bootcamps (working title)',
  subtitle: '',
  article_text: '',
  article_link: '',
  notes: 'had a great conversation with some people at Prime Digital Academy. potential feature?',
  photo: '',
  type: '',
  copies_required: false,
  number_of_copies: 0,
  copies_sent: false,
  copies_destination: '',
  photo_uploaded: false,
  graphic_image_required: false,
  graphic_image_completed: false,
  fact_check_completed: false,
  payment_required: false,
  payment_completed: false,
  socials_required: false,
  socials_completed: false,
  underwriter_required: false,
  underwriter_completed: false,
  photo_submitted: false,
  photo_comments: '',
  external_link: '',
  word_count: 0,
  date_added: '',
  rough_draft_deadline: DateTime.now(),
  final_draft_deadline: DateTime.now().toISO(),
  publication_date: DateTime.now().toISO(),
  contacts: [],
  theme: [],
  tags: [{ id: 7, name: 'Technology', description: '' }],
};

//* step 2: go ahead with story. assign theme and dates

// export const autofill2 = {
//   id: '',
//   title: 'women in tech bootcamps (working title)',
//   subtitle: '',
//   article_text: '',
//   article_link: '',
//   notes: 'had a great conversation with some people at Prime Digital Academy. potential feature?',
//   photo: '',
//   type: '',
//   copies_required: false,
//   number_of_copies: 0,
//   copies_sent: false,
//   copies_destination: '',
//   photo_uploaded: false,
//   graphic_image_required: false,
//   graphic_image_completed: false,
//   fact_check_required: true,
//   fact_check_completed: false,
//   payment_required: false,
//   payment_completed: false,
//   socials_required: true,
//   socials_completed: false,
//   underwriter_required: false,
//   underwriter_completed: false,
//   photo_submitted: false,
//   photo_comments: 'picture of a student from prime',
//   external_link: '',
//   word_count: 500,
//   date_added: '',
//   rough_draft_deadline: DateTime.fromObject({ day: 1, month: 8, year: 2023 }).toISO(),
//   final_draft_deadline: DateTime.fromObject({ day: 15, month: 8, year: 2023 }).toISO(),
//   publication_date: DateTime.fromObject({ day: 1, month: 9, year: 2023 }).toISO(),
//   contacts: [],
//   theme: [
//     {
//       "id": 9,
//       "name": "Work",
//       "description": "The ways our work lives are shifting — including the role of labor unions, anti-racist movements in the workplace, and changing family leave practices.\nSpecial sections: Directory, Elder, Travel & Adventure",
//       "month_year": "2023-09-01T05:00:00.000Z",
//       "stories": [
//         {
//           "id": 53,
//           "title": "Accelerated: Women in Technology",
//           "subtitle": "",
//           "article_text": "",
//           "article_link": "",
//           "notes": "had a great conversation with some people at Prime Digital Academy. potential feature?",
//           "photo": "",
//           "type": "",
//           "copies_required": false,
//           "number_of_copies": 0,
//           "copies_sent": false,
//           "photo_uploaded": true,
//           "fact_check_required": true,
//           "fact_check_completed": true,
//           "graphic_image_required": false,
//           "graphic_image_completed": false,
//           "payment_required": true,
//           "payment_completed": true,
//           "external_link": "",
//           "word_count": 0,
//           "date_added": "2023-02-12",
//           "rough_draft_deadline": "2022-02-17",
//           "final_draft_deadline": "2022-02-24",
//           "publication_date": "2022-02-25",
//           "copies_destination": "",
//           "socials_required": true,
//           "socials_completed": true,
//           "underwriter_required": false,
//           "underwriter_completed": false,
//           "photo_submitted": false,
//           "photo_comments": ""
//         }
//       ],
//       "contacts": [
//         {
//           "id": 12,
//           "name": "Savannah Howe",
//           "pronouns": null,
//           "expertise": null,
//           "photo": null,
//           "email": null,
//           "phone": null,
//           "billing_address": null,
//           "mailing_address": null,
//           "bio": null,
//           "note": null,
//           "linkedIn": null,
//           "twitter": null,
//           "instagram": null,
//           "facebook": null,
//           "date_added": "2023-02-07"
//         },
//         {
//           "id": 15,
//           "name": "Nikki Pieratos",
//           "pronouns": null,
//           "expertise": null,
//           "photo": null,
//           "email": null,
//           "phone": null,
//           "billing_address": null,
//           "mailing_address": null,
//           "bio": null,
//           "note": null,
//           "linkedIn": null,
//           "twitter": null,
//           "instagram": null,
//           "facebook": null,
//           "date_added": "2023-02-07"
//         },
//         {
//           "id": 18,
//           "name": "Sheila Regan",
//           "pronouns": null,
//           "expertise": null,
//           "photo": null,
//           "email": null,
//           "phone": null,
//           "billing_address": null,
//           "mailing_address": null,
//           "bio": null,
//           "note": null,
//           "linkedIn": null,
//           "twitter": null,
//           "instagram": null,
//           "facebook": null,
//           "date_added": "2023-02-07"
//         },
//         {
//           "id": 33,
//           "name": "Victoria Mertens",
//           "pronouns": "she/her",
//           "expertise": "Full-stack software engineer, Prime Digital Academy graduate",
//           "photo": null,
//           "email": "victoria.mertens44@gmail.com",
//           "phone": "",
//           "billing_address": "",
//           "mailing_address": "",
//           "bio": "",
//           "note": "",
//           "linkedIn": null,
//           "twitter": "",
//           "instagram": "",
//           "facebook": "",
//           "date_added": "2023-02-12"
//         }
//       ]
//     }
//   ],
//   tags: [{ id: 7, name: 'Technology', description: '' }],
// };

export const autofill2 = {
  "title": "women in tech bootcamps (working title)",
  "subtitle": "",
  "article_text": "",
  "article_link": "",
  "notes": "had a great conversation with some people at Prime Digital Academy. potential feature?",
  "photo": "",
  "type": "",
  "copies_required": false,
  "number_of_copies": 0,
  "copies_sent": false,
  "copies_destination": "",
  "photo_uploaded": false,
  "graphic_image_required": false,
  "graphic_image_completed": false,
  "fact_check_required": true,
  "fact_check_completed": false,
  "payment_required": false,
  "payment_completed": false,
  "socials_required": true,
  "socials_completed": false,
  "underwriter_required": false,
  "underwriter_completed": false,
  "photo_submitted": false,
  "photo_comments": "picture of a student from prime",
  "external_link": "",
  "word_count": "500",
  "date_added": "2023-02-12T06:00:00.000Z",
  "rough_draft_deadline": "2023-08-01T00:00:00.000-05:00",
  "final_draft_deadline": "2023-08-15T00:00:00.000-05:00",
  "publication_date": "2023-09-01T00:00:00.000-05:00",
  "contacts": [],
  "theme": [
      {
          "id": 9,
          "name": "Work",
          "description": "The ways our work lives are shifting — including the role of labor unions, anti-racist movements in the workplace, and changing family leave practices.\nSpecial sections: Directory, Elder, Travel & Adventure",
          "month_year": "2023-09-01T05:00:00.000Z",
          "stories": [
              {
                  "id": 53,
                  "title": "Accelerated: Women in Technology",
                  "subtitle": "",
                  "article_text": "",
                  "article_link": "",
                  "notes": "had a great conversation with some people at Prime Digital Academy. potential feature?",
                  "photo": "",
                  "type": "",
                  "copies_required": false,
                  "number_of_copies": 0,
                  "copies_sent": false,
                  "photo_uploaded": true,
                  "fact_check_required": true,
                  "fact_check_completed": true,
                  "graphic_image_required": false,
                  "graphic_image_completed": false,
                  "payment_required": true,
                  "payment_completed": true,
                  "external_link": "",
                  "word_count": 0,
                  "date_added": "2023-02-12",
                  "rough_draft_deadline": "2022-02-17",
                  "final_draft_deadline": "2022-02-24",
                  "publication_date": "2022-02-25",
                  "copies_destination": "",
                  "socials_required": true,
                  "socials_completed": true,
                  "underwriter_required": false,
                  "underwriter_completed": false,
                  "photo_submitted": false,
                  "photo_comments": ""
              }
          ],
          "contacts": [
              {
                  "id": 12,
                  "name": "Savannah Howe",
                  "pronouns": null,
                  "expertise": null,
                  "photo": null,
                  "email": null,
                  "phone": null,
                  "billing_address": null,
                  "mailing_address": null,
                  "bio": null,
                  "note": null,
                  "linkedIn": null,
                  "twitter": null,
                  "instagram": null,
                  "facebook": null,
                  "date_added": "2023-02-07"
              },
              {
                  "id": 15,
                  "name": "Nikki Pieratos",
                  "pronouns": null,
                  "expertise": null,
                  "photo": null,
                  "email": null,
                  "phone": null,
                  "billing_address": null,
                  "mailing_address": null,
                  "bio": null,
                  "note": null,
                  "linkedIn": null,
                  "twitter": null,
                  "instagram": null,
                  "facebook": null,
                  "date_added": "2023-02-07"
              },
              {
                  "id": 18,
                  "name": "Sheila Regan",
                  "pronouns": null,
                  "expertise": null,
                  "photo": null,
                  "email": null,
                  "phone": null,
                  "billing_address": null,
                  "mailing_address": null,
                  "bio": null,
                  "note": null,
                  "linkedIn": null,
                  "twitter": null,
                  "instagram": null,
                  "facebook": null,
                  "date_added": "2023-02-07"
              },
              {
                  "id": 33,
                  "name": "Victoria Mertens",
                  "pronouns": "she/her",
                  "expertise": "Full-stack software engineer, Prime Digital Academy graduate",
                  "photo": null,
                  "email": "victoria.mertens44@gmail.com",
                  "phone": "",
                  "billing_address": "",
                  "mailing_address": "",
                  "bio": "",
                  "note": "",
                  "linkedIn": null,
                  "twitter": "",
                  "instagram": "",
                  "facebook": "",
                  "date_added": "2023-02-12"
              }
          ]
      }
  ],
  "tags": [
      {
          "id": 7,
          "name": "Technology",
          "description": ""
      }
  ],
  "statusColor": {
      "color": "grey.100",
      "notes": "story has not been assigned deadlines"
  }
}

//* step 3: story is set. assign contacts. 

export const autofillContact = {
  "name": "Victoria Mertens",
  "pronouns": "she/her",
  "expertise": "Full-stack software engineer, Prime Digital Academy graduate",
  "email": "victoria.mertens44@gmail.com",
  "phone": "",
  "billing_address": "",
  "mailing_address": "",
  "bio": "",
  "note": "",
  "linkedIn": "",
  "twitter": "",
  "instagram": "",
  "facebook": "",
  "tags": [],
  "roles": []
}

export const autofill3 = {
  title: 'Accelerated: Women in Tech',
  subtitle: '',
  article_text: '',
  article_link: '',
  notes: 'had a great conversation with some people at Prime Digital Academy. potential feature? \t\ interviews with graduates, current students, alums',
  photo: '',
  type: '',
  copies_required: false,
  number_of_copies: null,
  copies_sent: false,
  photo_uploaded: false,
  graphic_image_required: false,
  graphic_image_completed: false,
  fact_check_required: true,
  fact_check_completed: false,
  payment_required: false,
  payment_completed: false,
  socials_required: true,
  socials_completed: false,
  underwriter_required: false,
  underwriter_completed: false,
  photo_submitted: false,
  photo_comments: 'picture of a student from prime',
  external_link: '',
  word_count: 500,
  date_added: '',
  rough_draft_deadline: DateTime.fromObject({ day: 1, month: 8, year: 2023 }).toISO(),
  final_draft_deadline: DateTime.fromObject({ day: 15, month: 8, year: 2023 }).toISO(),
  publication_date: DateTime.fromObject({ day: 1, month: 9, year: 2023 }).toISO(),
  contacts: [],
  theme: [{
    id: 9,
    name: 'Work',
    month_year: DateTime.fromISO('2023-09-01T05:00:00.000Z'),
    description: 'The ways our work lives are shifting — including the role of labor unions, anti-racist movements in the workplace, and changing family leave practices. Special sections: Directory, Elder, Travel & Adventure'
  }],
  tags: [{ id: 7, name: 'Technology', description: '' }],
};

//* step 4: 